// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyAbtyS2KykIPVN7yf770krM4g5lMAftk',
    appId: '1:769805574561:web:363b91161fba6910db2be0',
    messagingSenderId: '769805574561',
    projectId: 'talkup-74a06',
    authDomain: 'talkup-74a06.firebaseapp.com',
    storageBucket: 'talkup-74a06.appspot.com',
    measurementId: 'G-JNCL740R9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMFB2xlfNDCVLK8KsGUMHn5Rv3pXSs9RE',
    appId: '1:769805574561:android:825a5289d86288dbdb2be0',
    messagingSenderId: '769805574561',
    projectId: 'talkup-74a06',
    storageBucket: 'talkup-74a06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALahCUT5fy3QsScRmfN2TB-0bERj1bJSQ',
    appId: '1:769805574561:ios:93eefcd7677ce2a6db2be0',
    messagingSenderId: '769805574561',
    projectId: 'talkup-74a06',
    storageBucket: 'talkup-74a06.appspot.com',
    iosBundleId: 'com.example.talkUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALahCUT5fy3QsScRmfN2TB-0bERj1bJSQ',
    appId: '1:769805574561:ios:93eefcd7677ce2a6db2be0',
    messagingSenderId: '769805574561',
    projectId: 'talkup-74a06',
    storageBucket: 'talkup-74a06.appspot.com',
    iosBundleId: 'com.example.talkUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyAbtyS2KykIPVN7yf770krM4g5lMAftk',
    appId: '1:769805574561:web:4654dfda1adb1cf0db2be0',
    messagingSenderId: '769805574561',
    projectId: 'talkup-74a06',
    authDomain: 'talkup-74a06.firebaseapp.com',
    storageBucket: 'talkup-74a06.appspot.com',
    measurementId: 'G-P5LTMBNCNS',
  );
}
